### ISSUE TITLE
where is esp_camera.h

### ISSUE THREAD

**Issue by assegid** [dproldan/Esp32AutoCamera#3]
hello, I was going to test your code on a TTGO T- camera  board with the Arduino IDE selecting esp32 dev module as a board because I could not find the option for Wrover. Compiling returns  'file not found' for esp_camera.h. Where can I get that?

**Comment by dproldan** [comment]
Make sure you have the ESP32 board definition in the Arduino IDE.   Follow the instructions here,  for example:
https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/

**Comment by assegid** [comment]
The board definition is already there and I have been using the esp32 for a while for other applications. Are you developing using the IDF or the Arduino IDE? Have you tested your system with the Arduino IDE? If so, can you direct me to more detailed instructions? As I said, currently, I am not even sure if I have selected the correct hardware in the IDE. There are no options for Wrover or TTGO.

**Comment by pfeerick** [comment]
@assegid Did you resolve this? This code looks to be a modification of the CameraWebServer example provided with the ESP32 Arduino core... as is hinted by the note that it is:
> a mash-up of some of the example programs for the ESP32

The fact that you don't have the `ESP32 Wrover` board option suggests either you missed it in the list, or something is wrong with your configuration, as it is a stock board, present since at least the  Jul 28, 2018 release of v1.0.0 of the ESP32 Arduino core... 😱 

![image](https://user-images.githubusercontent.com/5500713/66712448-19a1c480-ede0-11e9-888c-0e38ba5749ad.png)
